### ISSUE TITLE
failing image format tests

### ISSUE THREAD

**Issue by frispete** [cbrunet/python-poppler#29] opened 2021-03-22 01:34 UTC
Hi Charles,

I found 0.2.2 builds failing for some time in our distributions.
It turned out  to require a patch similar to:

```
Index: b/tests/test_image.py
===================================================================
--- a/tests/test_image.py
+++ b/tests/test_image.py
@@ -40,8 +40,8 @@ def test_data_size(pdf_page):


 def test_image_format_to_str():
-    assert str(Image.Format.argb32) == "BGRA"
-    assert str(Image.Format.invalid) == ""
+    assert str(Image.Format.argb32) in ("BGRA", "format_enum.argb32")
+    assert str(Image.Format.invalid) in ("", "format_enum.invalid")
 
 
 def test_image_memory_view(pdf_page):
```

It looks like being related to the pybind11 version, as we use the system provided one.

Is this intended? In other words, do you want me to prepare a PR with such a change, or do you plan to add some code to keep the old API?

If you want to check out my builds, look [here](https://build.opensuse.org/package/show/home:frispete:python/python-python-poppler?expand=1).

The openSUSE_Leap_15.2 build is using an older pybind11, while the other builds use the current release.

**Comment by cbrunet** [comment] 2021-03-22 01:48
This is due to a change in Pybind11 2.6 (https://pybind11.readthedocs.io/en/stable/advanced/functions.html#overload-resolution-order). This was already fixed in master at https://github.com/cbrunet/python-poppler/blob/5625ae333bed95e5be2e057b64cb578650f95315/src/cpp/image.cpp#L96 (with the `py::prepend()` )

The test is testing for the intended behavior (I want to be able to cast the Format enum to str). Therefore, your proposed change to the test would not be acceptable.

I see no reason to prefer the system version of Pybind11 to the bundled one, since it is header only. This way, I'm sure the code remains compatible with the given pybind11 version, and I do not need to support many versions together.

**Closed by cbrunet** 2021-03-22 01:48 UTC

**Comment by frispete** [comment] 2021-03-24 19:30
Thanks for the pointer, Charles.

I adjusted my patch accordingly. 

The rationale of building with the system provided one is adhering to data minimization. Of course, I should have been able to read out the relevant changes from your commits without outside help. Sorry.
